#!/usr/bin/ruby

def gear_info(tokens, gear_id, &block)
  gears = {}
  if tokens.length == 1
    gears[gear_id] = tokens.first
  else
    puts tokens.inspect
    while not tokens.empty?
      gear, delim, data = tokens.shift(3)
      data = yield data if block_given?
      raise "Invalid data" unless delim == '='
      gears[gear] = data
      tokens.shift if tokens.first == ' '
    end
  end
  gears
end

def tokenize(s)
  tokens = []
  a = ""
  state = :start
  s.scan(/([ \t]+)|(\\')|(')|([^ \t']+)/) do |args|
    space, escaped_delim, delim, text = args
    case state
    when :start
      case
      when space then " "
      when escaped_delim then raise "Unexpected delimiter"
      when delim then state = :within_delim
      when text then tokens << text
      else raise "error"
      end
    when :within_delim
      case
      when space then a << space
      when escaped_delim then a << '"'
      when delim then tokens << a; a = ""; state = :start
      when text then a << text
      end
    end
  end
  tokens << a if a.length > 0
  tokens
end

gear_id = ARGV.shift
domain = ARGV.shift
tokens = tokenize(ARGV.shift)

# better if this is in creation order (oldest first)
gears = gear_info(tokens, gear_id) do |d| 
  d.split(/;? /).map{ |s| s.split('=', 2) }.inject({}){ |h, (k,v)| h[k] = v if v != ';'; h }
end
gears.each_pair{ |k,v| puts "Found gear #{k}#{k == gear_id ? '* ' : ''} with data #{v.inspect}" }

master = ENV['REDIS_PREFERRED_MASTER'] || gears.keys.sort.first
IO.write('env/REDIS_PREFERRED_MASTER', master)
IO.write('env/REDIS_PASSWORD', gears[master]['OPENSHIFT_REDIS_DB_PASSWORD'] || ENV['REDIS_PASSWORD'])
hosts = gears.map{ |k,v| v['OPENSHIFT_REDIS_DB_HOST'] }.compact.uniq.sort
IO.write('env/REDIS_KNOWN_HOSTS', hosts.join(','))